### ISSUE TITLE
Cannot find module 'gm'

### ISSUE THREAD

**Issue by jojo786** [aws-samples/serverless-face-blur-service#1]
The BlurFunction Lambda throws this error:

{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'gm'\nRequire stack:\n- /var/task/blurFaces.js\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'gm'",
        "Require stack:",
        "- /var/task/blurFaces.js",
        "- /var/task/app.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}

**Comment by satrya070** [comment]
Unfortunately this still doesn't work and still throws this error, for anyone trying it out.

**Comment by Stijnp** [comment]
I ran into the same problem earlier today, you'll have to do `npm install` in the src folder before running the sam stack. This will create the folder node_modules which will be copied to your lambda function.
